// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0rop1y1Nm9JZ42BtAQZ_zcIoLo3NgVBQ',
    appId: '1:976316591387:web:8314ecec920f9f3d1cf7be',
    messagingSenderId: '976316591387',
    projectId: 'burger-tik',
    authDomain: 'burger-tik.firebaseapp.com',
    storageBucket: 'burger-tik.appspot.com',
    measurementId: 'G-BK17YCVHL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnyLKNVXmg1YFQ26oMhceHu3LJIb9OCqI',
    appId: '1:976316591387:android:dc838acb5ebc5a231cf7be',
    messagingSenderId: '976316591387',
    projectId: 'burger-tik',
    storageBucket: 'burger-tik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QNQ1mYits_P8WKzgOisEnxlT5RUstVM',
    appId: '1:976316591387:ios:494026934756a1db1cf7be',
    messagingSenderId: '976316591387',
    projectId: 'burger-tik',
    storageBucket: 'burger-tik.appspot.com',
    androidClientId: '976316591387-3eiijq1e7a91203gl197l57ukh26rjl4.apps.googleusercontent.com',
    iosClientId: '976316591387-66v3bptk22dl6bjeaqmmdjul5b915ams.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );
}
